[jimff]
title = "제천국제음악영화제"
url = "https://www.vlive.tv/channel/B069D9/board/6114?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[jimff_notice]
title = "제천국제음악영화제 ─ 공지사항"
url = "https://www.vlive.tv/channel/B069D9/board/2601?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[bifan]
title = "부천국제판타스틱영화제"
url = "https://www.vlive.tv/channel/B3497D/board/6039?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[bifan_notice]
title = "부천국제판타스틱영화제 ─ 공지사항"
url = "https://www.vlive.tv/channel/B3497D/board/2483?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[biff]
title = "부산국제영화제"
url = "https://www.vlive.tv/channel/AD1A43/board/6213?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[biff_notice]
title = "부산국제영화제 ─ 공지사항"
url = "https://www.vlive.tv/channel/AD1A43/board/2723?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
contentSelector = "div[class^='writer_area'] em"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[jeonjuitt]
title = "전주국제영화제"
url = "https://www.vlive.tv/channel/B4E949/board/5981?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[jeonjuitt_notice]
title = "전주국제영화제 ─ 공지사항"
url = "https://www.vlive.tv/channel/B4E949/board/2417?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
dateSelector = "span[class^='upload_time']"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"
